In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
plays=pd.read_csv(r'drive/MyDrive/final_bpml/scrapped_data_baru.csv')
plays.head().shape
plays.shape

(10000, 4)

In [ ]:
plays = plays.rename(columns={'content': 'text'})
plays

,userName,score,at,text
0,Pengguna Google,5,2025-02-23 04:23:21,Good
1,Pengguna Google,5,2025-02-22 23:16:01,Nge tutor nya ramah dan mudah di mengerti suka...
2,Pengguna Google,5,2025-02-22 15:36:55,Aplikasi yang bisa menginspirasi orang-orang a...
3,Pengguna Google,5,2025-02-22 15:31:22,Aplikasi nya bagus banget🤩🤩🤩 Terus banyak fitu...
4,Pengguna Google,3,2025-02-22 13:11:50,Kenapa ga bisa offline
...,...,...,...,...
9995,Pengguna Google,5,2022-08-25 08:47:15,Keren
9996,Pengguna Google,5,2022-08-25 08:40:06,Aplikasi yang benar benar membantu
9997,Pengguna Google,1,2022-08-25 07:41:11,"Gk guna, gk ramah dan gk bagus"
9998,Pengguna Google,2,2022-08-25 06:30:05,Aplikasi nya sangat menyenang kan dan penjelas...
9999,Pengguna Google,5,2022-08-25 06:17:35,Makasih ya ruang guru udah bikin aplikasi ini ...

# **CLEANING DATA**

In [ ]:
import re, string
import nltk

In [ ]:
!pip install Sastrawi

Collecting Sastrawi
  Downloading Sastrawi-1.0.1-py2.py3-none-any.whl.metadata (909 bytes)
Downloading Sastrawi-1.0.1-py2.py3-none-any.whl (209 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.7/209.7 kB 11.9 MB/s eta 0:00:00
Installing collected packages: Sastrawi
Successfully installed Sastrawi-1.0.1

In [ ]:
# from nltk.corpus import stopwords
from nltk.corpus import stopwords
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

import nltk
nltk.download('stopwords')
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize
import warnings
warnings.filterwarnings("ignore")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

In [ ]:
#Remove punctuations, links, stopwords, mentions and \r\n new line characters
def cleaningText(text):
  if isinstance(text, str):
    text=re.sub(r'@[A-Za-z0-9]+', '', text)
    text=re.sub(r'#[A-Za-z0-9]+', '', text)
    text=re.sub(r'RT[\s]', '', text)
    text=re.sub(r"http\S+", '', text)
    text=re.sub(r'[0-9]', '', text)

    text=text.replace('\n', ' ')
    text=text.translate(str.maketrans('', '', string.punctuation))
    text=text.strip(' ')
    return text
  else:
        return ""

def casefoldingText(text):
    text=text.lower()
    return text

def tokenizingText(text):
    text=word_tokenize(text)
    return text

def filteringText(text):
    listStopwords = set(stopwords.words('indonesian'))
    filtered=[]
    for txt in text:
      if txt not in listStopwords:
        filtered.append(txt)
    text=filtered
    return text

def stemmingText(text):
    factory = StemmerFactory()
    stemmer = factory.create_stemmer()
    text=[stemmer.stem(word) for word in text]
    return text

def toSentence(list_words):
    sentence = ' '.join(word for word in list_words)
    return sentence

In [ ]:
def strip_emoji(text):
  emoji_pattern = re.compile("["
  u"\U0001F600-\U0001F64F"  # emoticon
  u"\U0001F300-\U0001F5FF"  # simbol & transportasi
  u"\U0001F680-\U0001F6FF"  # transportasi
  u"\U0001F700-\U0001F77F"  # alat olahraga
  u"\U0001F780-\U0001F7FF"  # bendera
  u"\U0001F800-\U0001F8FF"  # suplemen emoji
  u"\U0001F900-\U0001F9FF"  # emoji wajah
  u"\U0001FA00-\U0001FA6F"  # emoji tangan
  u"\U0001FA70-\U0001FAFF"  # alat olahraga
  u"\U0001F004-\U0001F0CF"  # kartu domino
  u"\U0001F170-\U0001F251"  # simbol
  u"\U0001F300-\U0001F5FF"  # simbol & transportasi
  u"\U0001F600-\U0001F64F"  # emoticon
  u"\U0001F680-\U0001F6FF"  # transportasi
  u"\U0001F700-\U0001F77F"  # alat olahraga"
  u"\U0001F780-\U0001F7FF"  # bendera
  u"\U0001F800-\U0001F8FF"  # suplemen emoji
  u"\U0001F900-\U0001F9FF"  # emoji wajah
  u"\U0001FA00-\U0001FA6F"  # emoji tangan
  u"\U0001FA70-\U0001FAFF"  # alat olahraga
  u"\U0001F004-\U0001F0CF"  # kartu domino
  u"\U0001F170-\U0001F251"  # simbol"
  "]+", flags=re.UNICODE)
  text = emoji_pattern.sub(r"", text)
  return text

In [ ]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [ ]:
plays['text_clean']=plays['text'].apply(cleaningText)
plays['text_clean']=plays['text_clean'].apply(casefoldingText)
plays['text_clean']=plays['text_clean'].apply(strip_emoji)
plays.drop(['text'], axis=1,inplace=True)

plays['text_preprocessed']=plays['text_clean'].apply(tokenizingText)
plays['text_preprocessed']=plays['text_preprocessed'].apply(filteringText)
plays['text_preprocessed']=plays['text_preprocessed'].apply(stemmingText)

plays.drop_duplicates(subset=['text_clean'], inplace=True)

In [ ]:
plays.to_csv(r'drive/MyDrive/final_bpml/scrapped_data_clean.csv', index=False, header=True, index_label=None)

In [ ]:
df = pd.read_csv(r'drive/MyDrive/final_bpml/scrapped_data_clean.csv')
df

,userName,score,at,text_clean,text_preprocessed
0,Pengguna Google,5,2025-02-23 04:23:21,good,['good']
1,Pengguna Google,5,2025-02-22 23:16:01,nge tutor nya ramah dan mudah di mengerti suka...,"['nge', 'tutor', 'nya', 'ramah', 'mudah', 'ert..."
2,Pengguna Google,5,2025-02-22 15:36:55,aplikasi yang bisa menginspirasi orangorang ag...,"['aplikasi', 'inspirasi', 'orangorang', 'ajar'..."
3,Pengguna Google,5,2025-02-22 15:31:22,aplikasi nya bagus banget terus banyak fitur f...,"['aplikasi', 'nya', 'bagus', 'banget', 'fitur'..."
4,Pengguna Google,3,2025-02-22 13:11:50,kenapa ga bisa offline,"['ga', 'offline']"
...,...,...,...,...,...
8218,Pengguna Google,3,2022-08-25 09:10:03,ruang guru kalo nelpon jangan spamspam tolong ...,"['ruang', 'guru', 'kalo', 'nelpon', 'spamspam'..."
8219,Pengguna Google,5,2022-08-25 08:40:06,aplikasi yang benar benar membantu,"['aplikasi', 'bantu']"
8220,Pengguna Google,1,2022-08-25 07:41:11,gk guna gk ramah dan gk bagus,"['gk', 'gk', 'ramah', 'gk', 'bagus']"
8221,Pengguna Google,2,2022-08-25 06:30:05,aplikasi nya sangat menyenang kan dan penjelas...,"['aplikasi', 'nya', 'senang', 'jelas', 'nya', ..."
8222,Pengguna Google,5,2022-08-25 06:17:35,makasih ya ruang guru udah bikin aplikasi ini ...,"['makasih', 'ya', 'ruang', 'guru', 'udah', 'bi..."

# **PELABELAN LEXICON**

In [ ]:
lexicon_positive=dict()
import csv

with open('drive/MyDrive/final_bpml/positive.csv', mode='r') as csvfile:
    reader = csv.reader(csvfile, delimiter=',')
    for row in reader:
        lexicon_positive[row[0]] = int(row[1])

lexicon_negative=dict()
import csv
with open('drive/MyDrive/final_bpml/negative.csv', mode='r') as csvfile:
    reader = csv.reader(csvfile, delimiter=',')
    for row in reader:
        lexicon_negative[row[0]] = int(row[1])

def sentiment_analysis_lexicon_indonesia(text):
    score = 0
    for word in text:
        if (word in lexicon_positive):
            score = score + lexicon_positive[word]
    for word in text:
        if (word in lexicon_negative):
            score = score + lexicon_negative[word]
    polarity=''
    if (score > 0):
        polarity='positive'
    elif (score < 0):
        polarity='negative'
    else:
        polarity='neutral'
    return score, polarity

In [ ]:
results = plays['text_preprocessed'].apply(sentiment_analysis_lexicon_indonesia)
results=list(zip(*results))
plays['polarity_score'] = results[0]
plays['polarity']=results[1]
print(plays['polarity'].value_counts())
plays.shape

polarity
neutral     3945
positive    3188
negative    1090
Name: count, dtype: int64

(8223, 7)

# **PEMODELAN DATA**

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import pandas as pd
import numpy as np
df = pd.read_csv(r'drive/MyDrive/final_bpml/labelling.csv')
df

,userName,score,at,text_clean,text_preprocessed,polarity_score,polarity
0,Pengguna Google,5,2025-02-23 04:23:21,good,['good'],5,positive
1,Pengguna Google,5,2025-02-22 23:16:01,nge tutor nya ramah dan mudah di mengerti suka...,"['nge', 'tutor', 'nya', 'ramah', 'mudah', 'ert...",5,positive
2,Pengguna Google,5,2025-02-22 15:36:55,aplikasi yang bisa menginspirasi orangorang ag...,"['aplikasi', 'inspirasi', 'orangorang', 'ajar'...",0,neutral
3,Pengguna Google,5,2025-02-22 15:31:22,aplikasi nya bagus banget terus banyak fitur f...,"['aplikasi', 'nya', 'bagus', 'banget', 'fitur'...",6,positive
4,Pengguna Google,3,2025-02-22 13:11:50,kenapa ga bisa offline,"['ga', 'offline']",0,neutral
...,...,...,...,...,...,...,...
8218,Pengguna Google,3,2022-08-25 09:10:03,ruang guru kalo nelpon jangan spamspam tolong ...,"['ruang', 'guru', 'kalo', 'nelpon', 'spamspam'...",1,positive
8219,Pengguna Google,5,2022-08-25 08:40:06,aplikasi yang benar benar membantu,"['aplikasi', 'bantu']",0,neutral
8220,Pengguna Google,1,2022-08-25 07:41:11,gk guna gk ramah dan gk bagus,"['gk', 'gk', 'ramah', 'gk', 'bagus']",0,neutral
8221,Pengguna Google,2,2022-08-25 06:30:05,aplikasi nya sangat menyenang kan dan penjelas...,"['aplikasi', 'nya', 'senang', 'jelas', 'nya', ...",4,positive
8222,Pengguna Google,5,2022-08-25 06:17:35,makasih ya ruang guru udah bikin aplikasi ini ...,"['makasih', 'ya', 'ruang', 'guru', 'udah', 'bi...",4,positive

In [3]:
sentiment_mapping = {'neutral': 0, 'negative': 1, 'positive': 2}
df['polarity'] = df['polarity'].map(sentiment_mapping)

df = df[['text_clean', 'polarity']]
df

                                             text_clean  polarity
0                                                  good         2
1     nge tutor nya ramah dan mudah di mengerti suka...         2
2     aplikasi yang bisa menginspirasi orangorang ag...         0
3     aplikasi nya bagus banget terus banyak fitur f...         2
4                                kenapa ga bisa offline         0
...                                                 ...       ...
8218  ruang guru kalo nelpon jangan spamspam tolong ...         2
8219                 aplikasi yang benar benar membantu         0
8220                      gk guna gk ramah dan gk bagus         0
8221  aplikasi nya sangat menyenang kan dan penjelas...         2
8222  makasih ya ruang guru udah bikin aplikasi ini ...         2

[8223 rows x 2 columns]

In [4]:
class CountVectorizer:
    def __init__(self, max_features=None):
        self.max_features = max_features
        self.vocabulary = None
        self.vocabulary_mapping = None

    def fit(self, documents):
        word_counts = {}
        for doc in documents:
            words = doc.split()
            for word in words:
                if word in word_counts:
                    word_counts[word] += 1
                else:
                    word_counts[word] = 1

        # Sort dan ambil hanya sejumlah max_features kata pertama
        sorted_words = sorted(word_counts, key=word_counts.get, reverse=True)
        if self.max_features:
            sorted_words = sorted_words[:self.max_features]

        self.vocabulary = sorted_words
        self.vocabulary_mapping = {word: idx for idx, word in enumerate(self.vocabulary)}

    def transform(self, documents):
        if self.vocabulary_mapping is None:
            raise ValueError("Fit the CountVectorizer first before transforming data.")

        X = []
        for doc in documents:
            word_counts = [0] * len(self.vocabulary)
            words = doc.split()
            for word in words:
                if word in self.vocabulary_mapping:
                    word_counts[self.vocabulary_mapping[word]] += 1
            X.append(word_counts)
        return X

    def get_feature_names(self):
        return self.vocabulary

In [5]:
df['text_clean'] = df['text_clean'].astype(str).fillna('')
corpus = df['text_clean'].tolist()
# cv = CountVectorizer()
# cv.fit(corpus)
cv_top = CountVectorizer()
cv_top.fit(corpus)
X_cv_top = cv_top.transform(corpus)

<ipython-input-5-8363388a5319>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['text_clean'] = df['text_clean'].astype(str).fillna('')

In [6]:
kata_unik = cv_top.get_feature_names()

# Menampilkan jumlah kata unik
print("Jumlah kata unik:", len(kata_unik))

# Menampilkan daftar kata unik
print("Daftar kata unik:", kata_unik)

Jumlah kata unik: 9940

# **EKSTRAKSI FITUR TF-IDF**

In [7]:
import math


class Tfidf:
    def fit(self, X):
        self.idf = [0] * len(X[0])
        N = len(X)

        # Menghitung IDF (Inverse Document Frequency) untuk setiap kata
        for i in range(len(X[0])):
            doc_count = sum([1 for doc in X if doc[i] > 0])
            if doc_count > 0:
                self.idf[i] = math.log(N / (doc_count+1))

    def transform(self, X):
        X_tf = []
        for doc in X:
            doc_tf = [tf * idf for tf, idf in zip(doc, self.idf)]
            X_tf.append(doc_tf)
        return X_tf

In [8]:
tfidf = Tfidf()
tfidf.fit(X_cv_top)
X_tf = tfidf.transform(X_cv_top)

# **Skenario Pembagian data 80:20 (TF-IDF, SVM)**

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_tf, df['polarity'], test_size=0.2, stratify=df['polarity'], random_state=42)

In [10]:
len(X_train)

6578

In [11]:
X_train_matrix = np.array(X_train)
print(X_train_matrix)

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [1.71759938 1.65713418 0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]

In [12]:
y_train.value_counts()

polarity
0    3156
2    2550
1     872
Name: count, dtype: int64

In [13]:
from imblearn.over_sampling import SMOTE

# Inisialisasi SMOTE
smote = SMOTE(sampling_strategy='auto', random_state=42)

# Transformasi data
X_resampled, y_resampled = smote.fit_resample(X_train, y_train)

# Cek distribusi setelah SMOTE
print(y_resampled.value_counts())

polarity
0    3156
2    3156
1    3156
Name: count, dtype: int64

In [14]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import LabelEncoder

svm_model = SVC(kernel='linear', C=1.0)

svm_model.fit(X_resampled, y_resampled)

y_pred = svm_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy: {accuracy:.4f}")
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Test Accuracy: 0.9112

Classification Report:
               precision    recall  f1-score   support

           0       0.90      0.97      0.93       789
           1       0.84      0.72      0.78       218
           2       0.95      0.90      0.93       638

    accuracy                           0.91      1645
   macro avg       0.90      0.87      0.88      1645
weighted avg       0.91      0.91      0.91      1645

# **Skenario Pembagian data 70:30 (TF-IDF, Decision Tree)**

In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv(r'drive/MyDrive/final_bpml/labelling.csv')

sentiment_mapping = {'neutral': 0, 'negative': 1, 'positive': 2}
df['polarity'] = df['polarity'].map(sentiment_mapping)

df = df[['text_clean', 'polarity']]

In [2]:
class CountVectorizer:
    def __init__(self, max_features=None):
        self.max_features = max_features
        self.vocabulary = None
        self.vocabulary_mapping = None

    def fit(self, documents):
        word_counts = {}
        for doc in documents:
            words = doc.split()
            for word in words:
                if word in word_counts:
                    word_counts[word] += 1
                else:
                    word_counts[word] = 1

        # Sort dan ambil hanya sejumlah max_features kata pertama
        sorted_words = sorted(word_counts, key=word_counts.get, reverse=True)
        if self.max_features:
            sorted_words = sorted_words[:self.max_features]

        self.vocabulary = sorted_words
        self.vocabulary_mapping = {word: idx for idx, word in enumerate(self.vocabulary)}

    def transform(self, documents):
        if self.vocabulary_mapping is None:
            raise ValueError("Fit the CountVectorizer first before transforming data.")

        X = []
        for doc in documents:
            word_counts = [0] * len(self.vocabulary)
            words = doc.split()
            for word in words:
                if word in self.vocabulary_mapping:
                    word_counts[self.vocabulary_mapping[word]] += 1
            X.append(word_counts)
        return X

    def get_feature_names(self):
        return self.vocabulary

In [3]:
df['text_clean'] = df['text_clean'].astype(str).fillna('')
corpus = df['text_clean'].tolist()
# cv = CountVectorizer()
# cv.fit(corpus)
cv_top = CountVectorizer()
cv_top.fit(corpus)
X_cv_top = cv_top.transform(corpus)

In [4]:
import math


class Tfidf:
    def fit(self, X):
        self.idf = [0] * len(X[0])
        N = len(X)

        # Menghitung IDF (Inverse Document Frequency) untuk setiap kata
        for i in range(len(X[0])):
            doc_count = sum([1 for doc in X if doc[i] > 0])
            if doc_count > 0:
                self.idf[i] = math.log(N / (doc_count+1))

    def transform(self, X):
        X_tf = []
        for doc in X:
            doc_tf = [tf * idf for tf, idf in zip(doc, self.idf)]
            X_tf.append(doc_tf)
        return X_tf

In [5]:
tfidf = Tfidf()
tfidf.fit(X_cv_top)
X_tf = tfidf.transform(X_cv_top)

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_tf, df['polarity'], test_size=0.3, stratify=df['polarity'], random_state=42)

In [7]:
len(X_train)

5756

In [8]:
X_train_matrix = np.array(X_train)
print(X_train_matrix)

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         1.52471949 ... 0.         0.         0.        ]
 ...
 [0.         3.31426837 1.52471949 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]

In [9]:
y_train.value_counts()

polarity
0    2761
2    2232
1     763
Name: count, dtype: int64

In [10]:
from imblearn.over_sampling import SMOTE

# Inisialisasi SMOTE
smote = SMOTE(sampling_strategy='auto', random_state=42)

# Transformasi data
X_resampled, y_resampled = smote.fit_resample(X_train, y_train)

# Cek distribusi setelah SMOTE
print(y_resampled.value_counts())

polarity
2    2761
0    2761
1    2761
Name: count, dtype: int64

In [11]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report

dt_model = DecisionTreeClassifier(max_depth=100, random_state=42)

dt_model.fit(X_train, y_train)

y_pred = dt_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy: {accuracy:.4f}")
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Test Accuracy: 0.8747

Classification Report:
               precision    recall  f1-score   support

           0       0.88      0.95      0.91      1184
           1       0.74      0.66      0.69       327
           2       0.91      0.86      0.88       956

    accuracy                           0.87      2467
   macro avg       0.84      0.82      0.83      2467
weighted avg       0.87      0.87      0.87      2467

# **Skenario Pembagian data 80:20 (TF-IDF, GRU)**

In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv(r'drive/MyDrive/final_bpml/labelling.csv')
df

sentiment_mapping = {'neutral': 0, 'negative': 1, 'positive': 2}
df['polarity'] = df['polarity'].map(sentiment_mapping)

df = df[['text_clean', 'polarity']]
df

                                             text_clean  polarity
0                                                  good         2
1     nge tutor nya ramah dan mudah di mengerti suka...         2
2     aplikasi yang bisa menginspirasi orangorang ag...         0
3     aplikasi nya bagus banget terus banyak fitur f...         2
4                                kenapa ga bisa offline         0
...                                                 ...       ...
8218  ruang guru kalo nelpon jangan spamspam tolong ...         2
8219                 aplikasi yang benar benar membantu         0
8220                      gk guna gk ramah dan gk bagus         0
8221  aplikasi nya sangat menyenang kan dan penjelas...         2
8222  makasih ya ruang guru udah bikin aplikasi ini ...         2

[8223 rows x 2 columns]

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, GRU, Embedding
from tensorflow.keras.optimizers import Adam
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

df['text_clean'] = df['text_clean'].astype(str).fillna('')

tfidf = TfidfVectorizer(max_features=5000)  # Ambil 5000 fitur kata paling penting
X_tfidf = tfidf.fit_transform(df['text_clean']).toarray()

X_train, X_test, y_train, y_test = train_test_split(X_tfidf, df['polarity'], test_size=0.2, random_state=42)

model = Sequential([
    Dense(512, activation='relu', input_shape=(X_train.shape[1],)),
    Dropout(0.3),
    Dense(256, activation='relu'),
    Dropout(0.3),
    Dense(128, activation='relu'),
    Dropout(0.3),
    Dense(len(np.unique(df['polarity'])), activation='softmax')
])

model.compile(loss='sparse_categorical_crossentropy', optimizer=Adam(learning_rate=0.001), metrics=['accuracy'])

history = model.fit(X_train, y_train, epochs=10, batch_size=64, validation_data=(X_test, y_test))

loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {accuracy:.4f}")

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 9s 68ms/step - accuracy: 0.5839 - loss: 0.8847 - val_accuracy: 0.8207 - val_loss: 0.4632
Epoch 2/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 5s 44ms/step - accuracy: 0.8999 - loss: 0.2776 - val_accuracy: 0.8875 - val_loss: 0.3367
Epoch 3/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 5s 45ms/step - accuracy: 0.9843 - loss: 0.0587 - val_accuracy: 0.8845 - val_loss: 0.4045
Epoch 4/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 6s 60ms/step - accuracy: 0.9966 - loss: 0.0165 - val_accuracy: 0.8906 - val_loss: 0.4540
Epoch 5/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 5s 44ms/step - accuracy: 0.9973 - loss: 0.0116 - val_accuracy: 0.8833 - val_loss: 0.4924
Epoch 6/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 10s 87ms/step - accuracy: 0.9996 - loss: 0.0033 - val_accuracy: 0.8979 - val_loss: 0.5261
Epoch 7/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 8s 77ms/step - accuracy: 0.9984 - loss: 0.0058 - val_accuracy: 0.8869 - val_loss: 0.5911
Epoch 8/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 10s 77ms/step - accuracy: 0.9999 - loss: 0.0014 - val_accuracy: 0.8833 - val_loss: 0.5860
Epoch 9/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 8s 75ms/step - accuracy: 0.9995 - loss: 0.0019 - val_accuracy: 0.8796 - val_loss: 0.6097
Epoch 10/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 7s 43ms/step - accuracy: 0.9990 - loss: 0.0029 - val_accuracy: 0.8857 - val_loss: 0.5761
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8834 - loss: 0.5749
Test Accuracy: 0.8857