In [ ]:
!pip install google-play-scraper

Collecting google-play-scraper
  Downloading google_play_scraper-1.2.7-py3-none-any.whl.metadata (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.2/50.2 kB 2.1 MB/s eta 0:00:00
Downloading google_play_scraper-1.2.7-py3-none-any.whl (28 kB)
Installing collected packages: google-play-scraper
Successfully installed google-play-scraper-1.2.7

In [ ]:
from google_play_scraper import app

import pandas as pd

import numpy as np

In [ ]:
from google_play_scraper import Sort, reviews_all

result = reviews_all(
    'com.ruangguru.livestudents',
    sleep_milliseconds=0,
    lang='id',
    country='id',
    sort=Sort.NEWEST,
    count=10000
)

In [ ]:
result = result[:10000]
del result[10000:]
print(len(result))

10000

In [ ]:
df_busu = pd.DataFrame(np.array(result),columns=['review'])

df_busu = df_busu.join(pd.DataFrame(df_busu.pop('review').tolist()))

df_busu.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,8e8e4f33-5947-4768-b808-828b5cf7c32f,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Good,5,0,None,2025-02-23 04:23:21,Thank you for the 5-star rating Nadya. We are ...,2025-02-23 05:59:25,None
1,626c8e5b-0661-482f-a651-4f95c0afd569,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Nge tutor nya ramah dan mudah di mengerti suka...,5,0,6.94.1,2025-02-22 23:16:01,Keren banget semangat belajar Nafisya. Makasih...,2025-02-23 03:17:41,6.94.1
2,d09619ad-36b8-4978-8507-d59b36777218,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Aplikasi yang bisa menginspirasi orang-orang a...,5,0,6.94.1,2025-02-22 15:36:55,Thanks Fiyandika buat bintang 5-nya. Seneng ba...,2025-02-23 03:13:06,6.94.1
3,0df36cd4-8b98-4de3-86a6-c30f7c2453dc,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Aplikasi nya bagus banget🤩🤩🤩 Terus banyak fitu...,5,0,6.94.0,2025-02-22 15:31:22,Thanks ya buat bintang 5-nya. Seneng deh Aplik...,2025-02-23 03:06:07,6.94.0
4,07146250-0934-456b-bf5d-72bce8aabdc6,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Kenapa ga bisa offline,3,0,None,2025-02-22 13:11:50,Hai Aris. Ruangguru bisa diakses secara offlin...,2025-02-23 03:28:02,None

In [ ]:
len(df_busu.index)

10000

In [ ]:
df_busu[['userName', 'score','at', 'content']].head()

,userName,score,at,content
0,Pengguna Google,5,2025-02-23 04:23:21,Good
1,Pengguna Google,5,2025-02-22 23:16:01,Nge tutor nya ramah dan mudah di mengerti suka...
2,Pengguna Google,5,2025-02-22 15:36:55,Aplikasi yang bisa menginspirasi orang-orang a...
3,Pengguna Google,5,2025-02-22 15:31:22,Aplikasi nya bagus banget🤩🤩🤩 Terus banyak fitu...
4,Pengguna Google,3,2025-02-22 13:11:50,Kenapa ga bisa offline

In [ ]:
new_df = df_busu[['userName', 'score','at', 'content']]
sorted_df = new_df.sort_values(by='at', ascending=False)
sorted_df.head()

,userName,score,at,content
0,Pengguna Google,5,2025-02-23 04:23:21,Good
1,Pengguna Google,5,2025-02-22 23:16:01,Nge tutor nya ramah dan mudah di mengerti suka...
2,Pengguna Google,5,2025-02-22 15:36:55,Aplikasi yang bisa menginspirasi orang-orang a...
3,Pengguna Google,5,2025-02-22 15:31:22,Aplikasi nya bagus banget🤩🤩🤩 Terus banyak fitu...
4,Pengguna Google,3,2025-02-22 13:11:50,Kenapa ga bisa offline

In [ ]:
my_df = sorted_df[['userName', 'score','at', 'content']]

In [ ]:
my_df.head()

,userName,score,at,content
0,Pengguna Google,5,2025-02-23 04:23:21,Good
1,Pengguna Google,5,2025-02-22 23:16:01,Nge tutor nya ramah dan mudah di mengerti suka...
2,Pengguna Google,5,2025-02-22 15:36:55,Aplikasi yang bisa menginspirasi orang-orang a...
3,Pengguna Google,5,2025-02-22 15:31:22,Aplikasi nya bagus banget🤩🤩🤩 Terus banyak fitu...
4,Pengguna Google,3,2025-02-22 13:11:50,Kenapa ga bisa offline

In [ ]:
my_df.to_csv("scrapped_data_baru.csv", index = False)